INSERT INTO Ingredient (name) VALUES ('Tomaquet');
INSERT INTO Ingredient (name) VALUES ('Mozzarella');
INSERT INTO Ingredient (name) VALUES ('Pernil');
INSERT INTO Ingredient (name) VALUES ('Pinya');
INSERT INTO Ingredient (name) VALUES ('Pollastre');
INSERT INTO Ingredient (name) VALUES ('Bacon Crispy');
INSERT INTO Ingredient (name) VALUES ('Frankfurt');
INSERT INTO Ingredient (name) VALUES ('Bacon');
INSERT INTO Ingredient (name) VALUES ('Ou');
INSERT INTO Ingredient (name) VALUES ('Salsitxes');
INSERT INTO Ingredient (name) VALUES ('Ceba');
INSERT INTO Ingredient (name) VALUES ('Mini Burgers');
INSERT INTO Ingredient (name) VALUES ('Tonyina');
INSERT INTO Ingredient (name) VALUES ('Xoriço');
INSERT INTO Ingredient (name) VALUES ('Olives');
INSERT INTO Ingredient (name) VALUES ('Salsa BBQ');
INSERT INTO Ingredient (name) VALUES ('Cheddar');
INSERT INTO Ingredient (name) VALUES ('Roquefort');
INSERT INTO Ingredient (name) VALUES ('Tomaquet Natural');
INSERT INTO Ingredient (name) VALUES ('Anxoves');
INSERT INTO Ingredient (name) VALUES ('Gambes');
INSERT INTO Ingredient (name) VALUES ('Carn');
INSERT INTO Ingredient (name) VALUES ('Salsa Carbonara');
INSERT INTO Ingredient (name) VALUES ('Xampinyons');
INSERT INTO Ingredient (name) VALUES ('Pernil Salat');
INSERT INTO Ingredient (name) VALUES ('Brie');
INSERT INTO Ingredient (name) VALUES ('Emmental');
INSERT INTO Ingredient (name) VALUES ('Pepperoni');
INSERT INTO Ingredient (name) VALUES ('Pebrot');
INSERT INTO Ingredient (name) VALUES ('Carxofa');
INSERT INTO Ingredient (name) VALUES ('Formatge Cabra');
INSERT INTO Ingredient (name) VALUES ('Sobrassada');
INSERT INTO Ingredient (name) VALUES ('Mel');

INSERT INTO Mass(name) VALUES('Original');
INSERT INTO Mass(name) VALUES('Prima');
INSERT INTO Mass(name) VALUES('Gruixuda');

INSERT INTO Drink(name) VALUES('Aigua');
INSERT INTO Drink(name) VALUES('Refresc');
INSERT INTO Drink(name) VALUES('Cervesa');

INSERT INTO Pizza(name) VALUES('Margarida');
INSERT INTO Pizza(name) VALUES('Hawaiana');
INSERT INTO Pizza(name) VALUES('Bacon Crispy');
INSERT INTO Pizza(name) VALUES('Americana');
INSERT INTO Pizza(name) VALUES('Traviata');
INSERT INTO Pizza(name) VALUES('Burger');
INSERT INTO Pizza(name) VALUES('Castellera');
INSERT INTO Pizza(name) VALUES('Cowboy');
INSERT INTO Pizza(name) VALUES('Vaquera');
INSERT INTO Pizza(name) VALUES('Marinera');
INSERT INTO Pizza(name) VALUES('Bbq');
INSERT INTO Pizza(name) VALUES('Diablo');
INSERT INTO Pizza(name) VALUES('Carbonara');
INSERT INTO Pizza(name) VALUES('Serrana');
INSERT INTO Pizza(name) VALUES('4 formatges');
INSERT INTO Pizza(name) VALUES('Pepperoni');
INSERT INTO Pizza(name) VALUES('Vegetal');
INSERT INTO Pizza(name) VALUES('Barcelona');
INSERT INTO Pizza(name) VALUES('Girona');
INSERT INTO Pizza(name) VALUES('Tarragona');
INSERT INTO Pizza(name) VALUES('Lleida');
INSERT INTO Pizza(name) VALUES('6 formatges');
INSERT INTO Pizza(name) VALUES('Mallorquina');
INSERT INTO Pizza(name) VALUES('Carbonara Deluxe');

INSERT INTO Delegation(name) VALUES('Barcelona');
INSERT INTO Delegation(name) VALUES('Lleida');
INSERT INTO Delegation(name) VALUES('Tarragona');
INSERT INTO Delegation(name) VALUES('Girona');